function context_menu_figure = view_analysis_gui()

handles.SCR = get(0,'Screensize');  % Get screensize.
context_menu_figure = figure('numbertitle','off',...
    'menubar','none',...
    'units','pixels',...
    'position',[handles.SCR(3)/2-200 ,handles.SCR(4)/2-700 , 400, 400],...
    'name','Context Menu',...
    'resize','off',...
    'visible','off');