function [] = bci_gem_pipeline()
% Demonstrate how to use toggle buttons to mimic tabbed panels.
% Creates a GUI with three toggle buttons which act as tabs.  One of the
% tabs is not selectable until the user plots a random quartic by
% pressing the pushbutton at the bottom of the screen.  The middle tab
% shows the result of fitting (with polyfit) a polynomial to the "unknown"
% quartic.
%
% Suggested exercise:  Add another tab which contains help info for how to
% use the GUI.
%
%
% Author:  Matt Fig
% Date:  7/15/2009
close all
handles.SCR = get(0,'Screensize');  % Get screensize.
%% Set Main Figures
handles.main_menu_figure = figure('numbertitle','off',...
    'menubar','none',...
    'units','pixels',...
    'position',[handles.SCR(3)/2-200 ,handles.SCR(4)/2-200 , 400, 400],...
    'name','Main Menu',...
    'resize','off');


handles.context_menu_figure = figure('numbertitle','off',...
    'menubar','none',...
    'units','pixels',...
    'position',[handles.SCR(3)/2-200 ,handles.SCR(4)/2-700 , 400, 400],...
    'name','Context Menu',...
    'resize','off',...
    'visible','off');

handles.context_figure = figure('numbertitle','off',...
    'menubar','none',...
    'units','pixels',...
    'position',[handles.SCR(3)/2+300 ,handles.SCR(4)/2-700 , 800, 900],...
    'name','Context Menu',...
    'resize','off',...
    'visible','off');

%% Set Main Menu Figures
handles.run_pipeline = uicontrol(handles.main_menu_figure,...
    'style','push',...
    'units','pix',...
    'position',[10 210 380 90],...
    'fontsize',14,...
    'string','Run Pipeline',...
    'callback',{@run_pipeline_call,handles});

handles.view_pipeline_settings= uicontrol(handles.main_menu_figure,...
    'style','push',...
    'units','pix',...
    'position',[10 110 380 90],...
    'fontsize',14,...
    'string','Pipeline Settings',...
    'callback',{@view_pipeline_settings_call,handles});

handles.view_analysis = uicontrol(handles.main_menu_figure,...
    'style','push',...
    'units','pix',...
    'position',[10 10 380 90],...
    'fontsize',14,...
    'string','View Analysis',...
    'callback',{@view_analysis_call,handles});


%%
function [] = view_analysis_call(varargin)
% Callback for pushbutton, deletes one line from listbox.
handles.analysis_gui = view_analysis_gui();
handles.analysis_gui


function [] = view_pipeline_settings_call(varargin)
handles = varargin{3};
handles.analysis_gui
close handles.analysis_gui;